services:
  app:
    build: .
    ports:
      - "80:3000"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://admin:sungbin123@mongodb:27017/wdj?authSource=admin
      - JWT_SECRET=eOwfeyPmLn9uUnqY
      - CORS_ORIGIN=https://wdj.kr,http://127.0.0.1:5500
      - NEIS_API_KEY=91f8dc8c8135439b8361d3540e05ec70
      - API_BASE_URL=http://116.123.74.248
    volumes:
      - ./uploads:/usr/src/app/uploads
    depends_on:
      - mongodb
    restart: unless-stopped
    networks:
      - app-network

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=sungbin123
      - MONGO_INITDB_DATABASE=wdj
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped
    networks:
      - app-network
    command: mongod --bind_ip_all --auth

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data:
